In [4]:
import numpy as np
import pandas as pd

In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
data_frame=pd.DataFrame(data)# thia is how you can make a dataframe from multiples series
data_frame

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
data_list2=pd.DataFrame(data_list)
data_list2
coloumn=['name','age','city','salary']
data_list3=pd.DataFrame(data_list,columns=coloumn)# this is how you can add coloums in a data frame
data_list3

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list3['name'] # this is you can acess ay coloumn of a data frame

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: object

In [9]:
data_list3[['name','city']] # this is how you can target multiples coloumn of dataframe

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [10]:
data_list3["designations"]=["doctor","enginier","not working","ex army"] # this is how you can add mutiple coulm of own

In [11]:
data_list3

    name  age      city  salary designations
0   John   28  New York   65000       doctor
1   Anna   34     Paris   70000     enginier
2  Peter   29    Berlin   62000  not working
3  Linda   42    London   85000      ex army

In [20]:
data_list3.drop('designations',axis=1)
data_list3

    name  age      city  salary designations
0   John   28  New York   65000       doctor
1   Anna   34     Paris   70000     enginier
2  Peter   29    Berlin   62000  not working
3  Linda   42    London   85000      ex army

In [21]:
print(data_list3.columns.tolist())

['name', 'age', 'city', 'salary', 'designations']

In [23]:
data_list3.drop('designations',axis=1,inplace=True) #this is how we actially delete data from the data list
data_list3

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
data_list3

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
data_list3.drop(0,axis=0) # this is how you cab delete any coloumn

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [28]:
data_list3.loc[1]  # this is the way to acess any locations

name       Anna
age          34
city      Paris
salary    70000
Name: 1, dtype: object

In [29]:
data_list3.loc[[1,2]] # this is how you can acess mutiple locations

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [32]:
data_list3.loc[[1,2]][["name","city","salary"]] # this is how we can celect perticuter aryea

    name    city  salary
1   Anna   Paris   70000
2  Peter  Berlin   62000

In [33]:
data_list3.loc[[2,3]][["city","salary"]]

     city  salary
2  Berlin   62000
3  London   85000

In [ ]:
 CONDITONAL STATE MENTs

In [34]:
data_list3[data_list3['age']>30] # thi is conditional state ment

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000