In [2]:
import numpy as np
import pandas as pd

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [14]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [15]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [6]:
pd.merge(employes,salaryes,on='employes_id',how='inner')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000

In [7]:
pd.merge(employes,salaryes,on='employes_id',how='outer')

   employes_id   name depertment    salary   bonus
0            1   john         hr   60000.0  2000.0
1            2   anna         it   34000.0  3000.0
2            3  peter    finance   23000.0  2000.0
3            4  linda         it       NaN     NaN
4            5    bob         hr       NaN     NaN
5            6    NaN        NaN  230000.0  3000.0
6            7    NaN        NaN   23400.0  2000.0

In [8]:
pd.merge(employes,salaryes,how='left')

   employes_id   name depertment   salary   bonus
0            1   john         hr  60000.0  2000.0
1            2   anna         it  34000.0  3000.0
2            3  peter    finance  23000.0  2000.0
3            4  linda         it      NaN     NaN
4            5    bob         hr      NaN     NaN

In [9]:
pd.merge(employes,salaryes,how='right')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000
3            6    NaN        NaN  230000   3000
4            7    NaN        NaN   23400   2000

In [ ]:
df1=({
    'A':['A0','A1','A3']
})