In [14]:
import pandas as pd
import numpy as np

In [15]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [16]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df1.shape #this helps to know thw shape of thre data frame

(5, 3)

In [5]:
df1.columns # thius hels to  know the colimns of the data type

Index(['A', 'B', 'C'], dtype='object')

In [6]:
df1.info() # this helps us tho knwoi thhe ifo of the data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [7]:
df1.describe()
# thius dscribes the detyails f tho data frame

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [8]:
df1['A']+10 
# THIS HELPS TP CHOOSE ANY COLOUMNS OF THE DATA FRAME

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [9]:
def squre(x):
    return x ** 2 # this is how we make a function ad make it apply where we need it

In [10]:
df1['B'] # this is how we apply the func

0    10
1    20
2    30
3    40
4    50
Name: B, dtype: int64

In [11]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [17]:
df1['D']=df1["B"].apply(lambda x : x**2) # by chnaging the name of the df you can make a new column

In [18]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500