In [2]:
import numpy as np
import pandas as pd

In [3]:
lists=[1,2,3,4,5]
labels=['a','b','c','d','e']
arr=np.array([1,2,3,4,5])

In [4]:
positions=pd.Series(labels,index=lists)

positions

1    a
2    b
3    c
4    d
5    e
dtype: object

In [5]:
arrayes=pd.Series(arr,index=labels)
arrayes

a    1
b    2
c    3
d    4
e    5
dtype: int64

THIS IS DATA FRAMES PRACTICE

In [6]:
data={
    'name':['john','shuvo','laxmi'],
    'age':[20,30,21],
    'city':['Nmglore','siliguri','odish']
    
}

In [7]:
details=pd.DataFrame(data)
details

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [12]:
details["salary"]=["$2000","$200","$20"]

In [13]:
details

    name  age      city salary
0   john   20   Nmglore  $2000
1  shuvo   30  siliguri   $200
2  laxmi   21     odish    $20

In [14]:
details.drop('salary',axis=1)

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [16]:
import numpy as np
import pandas as pd

In [17]:
copy={
    'name':['debmalya','samir','debjani','debanik'],
    'age':[20,63,54,26],
    'occupation':['bca student','ex gov techer','HM','job'],
    'sex':['male','male','female','male'],
    'marital status':['single','marred','marred','single'],
    
}
familly=pd.DataFrame(copy)

In [18]:
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [19]:
familly['adress']=['BBS','CCU','CCU','BLGR']

In [20]:
familly

       name  age     occupation     sex marital status adress
0  debmalya   20    bca student    male         single    BBS
1     samir   63  ex gov techer    male         marred    CCU
2   debjani   54             HM  female         marred    CCU
3   debanik   26            job    male         single   BLGR

In [24]:
familly.drop('adress',axis=1,inplace=True)
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [26]:
familly.loc[1]

name                      samir
age                          63
occupation        ex gov techer
sex                        male
marital status           marred
Name: 1, dtype: object

In [27]:
familly.loc[[0,2],['name','sex','occupation']]

       name     sex   occupation
0  debmalya    male  bca student
2   debjani  female           HM

In [28]:
familly[familly['age']>20]

      name  age     occupation     sex marital status
1    samir   63  ex gov techer    male         marred
2  debjani   54             HM  female         marred
3  debanik   26            job    male         single

In [31]:
familly[(familly['age']>20) &(familly['marital status']== 'single')]

      name  age occupation   sex marital status
3  debanik   26        job  male         single

In [1]:
import numpy as np
import pandas as pd

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [4]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [5]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [9]:
pd.merge(employes,salaryes,on='employes_id',how='inner')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000

In [10]:
pd.merge(employes,salaryes,on='employes_id',how='outer')

   employes_id   name depertment    salary   bonus
0            1   john         hr   60000.0  2000.0
1            2   anna         it   34000.0  3000.0
2            3  peter    finance   23000.0  2000.0
3            4  linda         it       NaN     NaN
4            5    bob         hr       NaN     NaN
5            6    NaN        NaN  230000.0  3000.0
6            7    NaN        NaN   23400.0  2000.0

In [12]:
pd.merge(employes,salaryes,how='left')

   employes_id   name depertment   salary   bonus
0            1   john         hr  60000.0  2000.0
1            2   anna         it  34000.0  3000.0
2            3  peter    finance  23000.0  2000.0
3            4  linda         it      NaN     NaN
4            5    bob         hr      NaN     NaN

In [13]:
pd.merge(employes,salaryes,how='right')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000
3            6    NaN        NaN  230000   3000
4            7    NaN        NaN   23400   2000

In [2]:
import pandas as pd
import numpy as np

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [4]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [5]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [13]:
pd.merge(salaryes,employes,on='employes_id',how='inner')

   employes_id  salary  bonus   name depertment
0            1   60000   2000   john         hr
1            2   34000   3000   anna         it
2            3   23000   2000  peter    finance

In [19]:
pd.merge(salaryes,employes,how='left')

   employes_id  salary  bonus   name depertment
0            1   60000   2000   john         hr
1            2   34000   3000   anna         it
2            3   23000   2000  peter    finance
3            6  230000   3000    NaN        NaN
4            7   23400   2000    NaN        NaN

In [22]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'A5'],
    'C': ['C3', 'C4', 'A5']
})

In [23]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [24]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  A5  A5

In [37]:
df1=pd.DataFrame({
    'name':['deb','rohan','samir','debjani']
},index=[1,2,3,4])

df2=pd.DataFrame({
    'profession':['student','job','ex teacher','teacher']
},index=[1,2,3,4])

In [38]:
df1

      name
1      deb
2    rohan
3    samir
4  debjani

In [39]:
df2

   profession
1     student
2         job
3  ex teacher
4     teacher

In [41]:
df1.join(df2)

      name  profession
1      deb     student
2    rohan         job
3    samir  ex teacher
4  debjani     teacher

In [43]:
pd.concat([df1,df2],axis=1)

      name  profession
1      deb     student
2    rohan         job
3    samir  ex teacher
4  debjani     teacher

In [20]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [5]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [9]:
df.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [13]:
labels=['a','b','c']
my_list=[1,2,3]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [14]:
pd.Series(my_list)

0    1
1    2
2    3
dtype: int64

In [15]:
pd.Series(my_list,index=labels)

a    1
b    2
c    3
dtype: int64

In [16]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [17]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [18]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [25]:
pd.merge(employes,salaryes,on='employes_id',how='inner')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000

In [27]:
pd.merge(employes,salaryes,how='right')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000
3            6    NaN        NaN  230000   3000
4            7    NaN        NaN   23400   2000

In [29]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'A5'],
    'C': ['C3', 'C4', 'A5']
})

In [30]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [31]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [32]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [35]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  A5  A5

In [37]:
df1=pd.DataFrame({
    'name':['alice','bob','charlie']
     
},index=[1,2,3])

df2=pd.DataFrame({
    'score':[23,56,54]
    
}, index=[2,3,4])

In [38]:
df1

      name
1    alice
2      bob
3  charlie

In [39]:
df2

   score
2     23
3     56
4     54

In [41]:
df1.join(df2,how='outer')

      name  score
1    alice    NaN
2      bob   23.0
3  charlie   56.0
4      NaN   54.0

In [42]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
data_list2=pd.DataFrame(data_list)
data_list2
coloumn=['name','age','city','salary']
data_list3=pd.DataFrame(data_list,columns=coloumn)# this is how you can add coloums in a data frame
data_list3

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [45]:
data_list3.loc[[1,2]][['name','age','city','salary']]

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [46]:
data_list3[(data_list3['age']>18)]

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
data_list3[(data_list3['age']>18) & (data_list3['city']=='paris')]

Empty DataFrame
Columns: [name, age, city, salary]
Index: []