In [2]:
import numpy as np
import pandas as pd

In [7]:
lists=[1,2,3,4,5]
labels=['a','b','c','d','e']
arr=np.array([1,2,3,4,5])

In [11]:
positions=pd.Series(labels,index=lists)

positions

1    a
2    b
3    c
4    d
5    e
dtype: object

In [12]:
arrayes=pd.Series(arr,index=labels)
arrayes

a    1
b    2
c    3
d    4
e    5
dtype: int64

THIS IS DATA FRAMES PRACTICE

In [13]:
data={
    'name':['john','shuvo','laxmi'],
    'age':[20,30,21],
    'city':['Nmglore','siliguri','odish']
    
}

In [15]:
details=pd.DataFrame(data)
details

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [17]:
details["salary"]=["$2000","$200","$20"]

In [18]:
details

    name  age      city salary
0   john   20   Nmglore  $2000
1  shuvo   30  siliguri   $200
2  laxmi   21     odish    $20

In [24]:
details.drop('salary',axis=1)

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish