In [2]:
import numpy as np
import pandas as pd

In [3]:
lists=[1,2,3,4,5]
labels=['a','b','c','d','e']
arr=np.array([1,2,3,4,5])

In [4]:
positions=pd.Series(labels,index=lists)

positions

1    a
2    b
3    c
4    d
5    e
dtype: object

In [5]:
arrayes=pd.Series(arr,index=labels)
arrayes

a    1
b    2
c    3
d    4
e    5
dtype: int64

THIS IS DATA FRAMES PRACTICE

In [6]:
data={
    'name':['john','shuvo','laxmi'],
    'age':[20,30,21],
    'city':['Nmglore','siliguri','odish']
    
}

In [7]:
details=pd.DataFrame(data)
details

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [12]:
details["salary"]=["$2000","$200","$20"]

In [13]:
details

    name  age      city salary
0   john   20   Nmglore  $2000
1  shuvo   30  siliguri   $200
2  laxmi   21     odish    $20

In [14]:
details.drop('salary',axis=1)

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [16]:
import numpy as np
import pandas as pd

In [17]:
copy={
    'name':['debmalya','samir','debjani','debanik'],
    'age':[20,63,54,26],
    'occupation':['bca student','ex gov techer','HM','job'],
    'sex':['male','male','female','male'],
    'marital status':['single','marred','marred','single'],
    
}
familly=pd.DataFrame(copy)

In [18]:
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [19]:
familly['adress']=['BBS','CCU','CCU','BLGR']

In [20]:
familly

       name  age     occupation     sex marital status adress
0  debmalya   20    bca student    male         single    BBS
1     samir   63  ex gov techer    male         marred    CCU
2   debjani   54             HM  female         marred    CCU
3   debanik   26            job    male         single   BLGR

In [24]:
familly.drop('adress',axis=1,inplace=True)
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [26]:
familly.loc[1]

name                      samir
age                          63
occupation        ex gov techer
sex                        male
marital status           marred
Name: 1, dtype: object

In [27]:
familly.loc[[0,2],['name','sex','occupation']]

       name     sex   occupation
0  debmalya    male  bca student
2   debjani  female           HM

In [28]:
familly[familly['age']>20]

      name  age     occupation     sex marital status
1    samir   63  ex gov techer    male         marred
2  debjani   54             HM  female         marred
3  debanik   26            job    male         single

In [31]:
familly[(familly['age']>20) &(familly['marital status']== 'single')]

      name  age occupation   sex marital status
3  debanik   26        job  male         single