In [2]:
import numpy as np
import pandas as pd

In [3]:
lists=[1,2,3,4,5]
labels=['a','b','c','d','e']
arr=np.array([1,2,3,4,5])

In [4]:
positions=pd.Series(labels,index=lists)

positions

1    a
2    b
3    c
4    d
5    e
dtype: object

In [5]:
arrayes=pd.Series(arr,index=labels)
arrayes

a    1
b    2
c    3
d    4
e    5
dtype: int64

THIS IS DATA FRAMES PRACTICE

In [6]:
data={
    'name':['john','shuvo','laxmi'],
    'age':[20,30,21],
    'city':['Nmglore','siliguri','odish']
    
}

In [7]:
details=pd.DataFrame(data)
details

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [12]:
details["salary"]=["$2000","$200","$20"]

In [13]:
details

    name  age      city salary
0   john   20   Nmglore  $2000
1  shuvo   30  siliguri   $200
2  laxmi   21     odish    $20

In [14]:
details.drop('salary',axis=1)

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [16]:
import numpy as np
import pandas as pd

In [17]:
copy={
    'name':['debmalya','samir','debjani','debanik'],
    'age':[20,63,54,26],
    'occupation':['bca student','ex gov techer','HM','job'],
    'sex':['male','male','female','male'],
    'marital status':['single','marred','marred','single'],
    
}
familly=pd.DataFrame(copy)

In [18]:
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [19]:
familly['adress']=['BBS','CCU','CCU','BLGR']

In [20]:
familly

       name  age     occupation     sex marital status adress
0  debmalya   20    bca student    male         single    BBS
1     samir   63  ex gov techer    male         marred    CCU
2   debjani   54             HM  female         marred    CCU
3   debanik   26            job    male         single   BLGR

In [24]:
familly.drop('adress',axis=1,inplace=True)
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [26]:
familly.loc[1]

name                      samir
age                          63
occupation        ex gov techer
sex                        male
marital status           marred
Name: 1, dtype: object

In [27]:
familly.loc[[0,2],['name','sex','occupation']]

       name     sex   occupation
0  debmalya    male  bca student
2   debjani  female           HM

In [28]:
familly[familly['age']>20]

      name  age     occupation     sex marital status
1    samir   63  ex gov techer    male         marred
2  debjani   54             HM  female         marred
3  debanik   26            job    male         single

In [31]:
familly[(familly['age']>20) &(familly['marital status']== 'single')]

      name  age occupation   sex marital status
3  debanik   26        job  male         single

In [1]:
import numpy as np
import pandas as pd

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [4]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [5]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [9]:
pd.merge(employes,salaryes,on='employes_id',how='inner')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000

In [10]:
pd.merge(employes,salaryes,on='employes_id',how='outer')

   employes_id   name depertment    salary   bonus
0            1   john         hr   60000.0  2000.0
1            2   anna         it   34000.0  3000.0
2            3  peter    finance   23000.0  2000.0
3            4  linda         it       NaN     NaN
4            5    bob         hr       NaN     NaN
5            6    NaN        NaN  230000.0  3000.0
6            7    NaN        NaN   23400.0  2000.0

In [12]:
pd.merge(employes,salaryes,how='left')

   employes_id   name depertment   salary   bonus
0            1   john         hr  60000.0  2000.0
1            2   anna         it  34000.0  3000.0
2            3  peter    finance  23000.0  2000.0
3            4  linda         it      NaN     NaN
4            5    bob         hr      NaN     NaN

In [13]:
pd.merge(employes,salaryes,how='right')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000
3            6    NaN        NaN  230000   3000
4            7    NaN        NaN   23400   2000

In [2]:
import pandas as pd
import numpy as np

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [4]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [5]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [13]:
pd.merge(salaryes,employes,on='employes_id',how='inner')

   employes_id  salary  bonus   name depertment
0            1   60000   2000   john         hr
1            2   34000   3000   anna         it
2            3   23000   2000  peter    finance

In [19]:
pd.merge(salaryes,employes,how='left')

   employes_id  salary  bonus   name depertment
0            1   60000   2000   john         hr
1            2   34000   3000   anna         it
2            3   23000   2000  peter    finance
3            6  230000   3000    NaN        NaN
4            7   23400   2000    NaN        NaN

In [22]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'A5'],
    'C': ['C3', 'C4', 'A5']
})

In [23]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [24]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  A5  A5

In [37]:
df1=pd.DataFrame({
    'name':['deb','rohan','samir','debjani']
},index=[1,2,3,4])

df2=pd.DataFrame({
    'profession':['student','job','ex teacher','teacher']
},index=[1,2,3,4])

In [38]:
df1

      name
1      deb
2    rohan
3    samir
4  debjani

In [39]:
df2

   profession
1     student
2         job
3  ex teacher
4     teacher

In [41]:
df1.join(df2)

      name  profession
1      deb     student
2    rohan         job
3    samir  ex teacher
4  debjani     teacher

In [43]:
pd.concat([df1,df2],axis=1)

      name  profession
1      deb     student
2    rohan         job
3    samir  ex teacher
4  debjani     teacher