In [2]:
import numpy as np
import pandas as pd

In [3]:
lists=[1,2,3,4,5]
labels=['a','b','c','d','e']
arr=np.array([1,2,3,4,5])

In [4]:
positions=pd.Series(labels,index=lists)

positions

1    a
2    b
3    c
4    d
5    e
dtype: object

In [5]:
arrayes=pd.Series(arr,index=labels)
arrayes

a    1
b    2
c    3
d    4
e    5
dtype: int64

THIS IS DATA FRAMES PRACTICE

In [6]:
data={
    'name':['john','shuvo','laxmi'],
    'age':[20,30,21],
    'city':['Nmglore','siliguri','odish']
    
}

In [7]:
details=pd.DataFrame(data)
details

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [12]:
details["salary"]=["$2000","$200","$20"]

In [13]:
details

    name  age      city salary
0   john   20   Nmglore  $2000
1  shuvo   30  siliguri   $200
2  laxmi   21     odish    $20

In [14]:
details.drop('salary',axis=1)

    name  age      city
0   john   20   Nmglore
1  shuvo   30  siliguri
2  laxmi   21     odish

In [16]:
import numpy as np
import pandas as pd

In [17]:
copy={
    'name':['debmalya','samir','debjani','debanik'],
    'age':[20,63,54,26],
    'occupation':['bca student','ex gov techer','HM','job'],
    'sex':['male','male','female','male'],
    'marital status':['single','marred','marred','single'],
    
}
familly=pd.DataFrame(copy)

In [18]:
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [19]:
familly['adress']=['BBS','CCU','CCU','BLGR']

In [20]:
familly

       name  age     occupation     sex marital status adress
0  debmalya   20    bca student    male         single    BBS
1     samir   63  ex gov techer    male         marred    CCU
2   debjani   54             HM  female         marred    CCU
3   debanik   26            job    male         single   BLGR

In [24]:
familly.drop('adress',axis=1,inplace=True)
familly

       name  age     occupation     sex marital status
0  debmalya   20    bca student    male         single
1     samir   63  ex gov techer    male         marred
2   debjani   54             HM  female         marred
3   debanik   26            job    male         single

In [26]:
familly.loc[1]

name                      samir
age                          63
occupation        ex gov techer
sex                        male
marital status           marred
Name: 1, dtype: object

In [27]:
familly.loc[[0,2],['name','sex','occupation']]

       name     sex   occupation
0  debmalya    male  bca student
2   debjani  female           HM

In [28]:
familly[familly['age']>20]

      name  age     occupation     sex marital status
1    samir   63  ex gov techer    male         marred
2  debjani   54             HM  female         marred
3  debanik   26            job    male         single

In [31]:
familly[(familly['age']>20) &(familly['marital status']== 'single')]

      name  age occupation   sex marital status
3  debanik   26        job  male         single

In [1]:
import numpy as np
import pandas as pd

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [4]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [5]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [9]:
pd.merge(employes,salaryes,on='employes_id',how='inner')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000

In [10]:
pd.merge(employes,salaryes,on='employes_id',how='outer')

   employes_id   name depertment    salary   bonus
0            1   john         hr   60000.0  2000.0
1            2   anna         it   34000.0  3000.0
2            3  peter    finance   23000.0  2000.0
3            4  linda         it       NaN     NaN
4            5    bob         hr       NaN     NaN
5            6    NaN        NaN  230000.0  3000.0
6            7    NaN        NaN   23400.0  2000.0

In [12]:
pd.merge(employes,salaryes,how='left')

   employes_id   name depertment   salary   bonus
0            1   john         hr  60000.0  2000.0
1            2   anna         it  34000.0  3000.0
2            3  peter    finance  23000.0  2000.0
3            4  linda         it      NaN     NaN
4            5    bob         hr      NaN     NaN

In [13]:
pd.merge(employes,salaryes,how='right')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000
3            6    NaN        NaN  230000   3000
4            7    NaN        NaN   23400   2000

In [2]:
import pandas as pd
import numpy as np

In [3]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [4]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [5]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [13]:
pd.merge(salaryes,employes,on='employes_id',how='inner')

   employes_id  salary  bonus   name depertment
0            1   60000   2000   john         hr
1            2   34000   3000   anna         it
2            3   23000   2000  peter    finance

In [19]:
pd.merge(salaryes,employes,how='left')

   employes_id  salary  bonus   name depertment
0            1   60000   2000   john         hr
1            2   34000   3000   anna         it
2            3   23000   2000  peter    finance
3            6  230000   3000    NaN        NaN
4            7   23400   2000    NaN        NaN

In [22]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'A5'],
    'C': ['C3', 'C4', 'A5']
})

In [23]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [24]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  A5  A5

In [37]:
df1=pd.DataFrame({
    'name':['deb','rohan','samir','debjani']
},index=[1,2,3,4])

df2=pd.DataFrame({
    'profession':['student','job','ex teacher','teacher']
},index=[1,2,3,4])

In [38]:
df1

      name
1      deb
2    rohan
3    samir
4  debjani

In [39]:
df2

   profession
1     student
2         job
3  ex teacher
4     teacher

In [41]:
df1.join(df2)

      name  profession
1      deb     student
2    rohan         job
3    samir  ex teacher
4  debjani     teacher

In [43]:
pd.concat([df1,df2],axis=1)

      name  profession
1      deb     student
2    rohan         job
3    samir  ex teacher
4  debjani     teacher

In [20]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [5]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [9]:
df.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [13]:
labels=['a','b','c']
my_list=[1,2,3]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [14]:
pd.Series(my_list)

0    1
1    2
2    3
dtype: int64

In [15]:
pd.Series(my_list,index=labels)

a    1
b    2
c    3
dtype: int64

In [16]:
employes=pd.DataFrame({
    'employes_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'depertment':['hr','it','finance','it','hr']
})
#depertment 2 salary info
salaryes=pd.DataFrame({
    'employes_id':[1,2,3,6,7],
    'salary':[60000,34000,23000,230000,23400],
    'bonus':[2000,3000,2000,3000,2000]
})

In [17]:
employes

   employes_id   name depertment
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [18]:
salaryes

   employes_id  salary  bonus
0            1   60000   2000
1            2   34000   3000
2            3   23000   2000
3            6  230000   3000
4            7   23400   2000

In [25]:
pd.merge(employes,salaryes,on='employes_id',how='inner')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000

In [27]:
pd.merge(employes,salaryes,how='right')

   employes_id   name depertment  salary  bonus
0            1   john         hr   60000   2000
1            2   anna         it   34000   3000
2            3  peter    finance   23000   2000
3            6    NaN        NaN  230000   3000
4            7    NaN        NaN   23400   2000

In [29]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'A5'],
    'C': ['C3', 'C4', 'A5']
})

In [30]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [31]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [32]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  A5  A5

In [35]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  A5  A5

In [37]:
df1=pd.DataFrame({
    'name':['alice','bob','charlie']
     
},index=[1,2,3])

df2=pd.DataFrame({
    'score':[23,56,54]
    
}, index=[2,3,4])

In [38]:
df1

      name
1    alice
2      bob
3  charlie

In [39]:
df2

   score
2     23
3     56
4     54

In [41]:
df1.join(df2,how='outer')

      name  score
1    alice    NaN
2      bob   23.0
3  charlie   56.0
4      NaN   54.0

In [42]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
data_list2=pd.DataFrame(data_list)
data_list2
coloumn=['name','age','city','salary']
data_list3=pd.DataFrame(data_list,columns=coloumn)# this is how you can add coloums in a data frame
data_list3

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [45]:
data_list3.loc[[1,2]][['name','age','city','salary']]

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [46]:
data_list3[(data_list3['age']>18)]

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
data_list3[(data_list3['age']>18) & (data_list3['city']=='paris')]

Empty DataFrame
Columns: [name, age, city, salary]
Index: []

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    636     75   John  January      Q1
1  2023-01-02       B   West    305     28   Mary  January      Q1
2  2023-01-03       C  North    584     74    Bob  January      Q1
3  2023-01-04       D  South    273     32  Alice  January      Q1
4  2023-01-05       A   East    582     84   John  January      Q1
5  2023-01-06       B   West    407     61   Mary  January      Q1
6  2023-01-07       C  North    711     95    Bob  January      Q1
7  2023-01-08       D  South    808     17  Alice  January      Q1
8  2023-01-09       A   East    660     75   John  January      Q1
9  2023-01-10       B   West    526     80   Mary  January      Q1
10 2023-01-11       C  North    838     92    Bob  January      Q1
11 2023-01-12       D  South    921     45  Alice  January      Q1
12 2023-01-13       A   East    225     44   John  January      Q1
13 2023-01-14       B   West    496     75   Mary  January      Q1
14 2023-01-15       C  North    458     57    Bob  January      Q1
15 2023-01-16       D  South    893     84  Alice  January      Q1
16 2023-01-17       A   East    356     73   John  January      Q1
17 2023-01-18       B   West    730     68   Mary  January      Q1
18 2023-01-19       C  North    556     64    Bob  January      Q1
19 2023-01-20       D  South    858     16  Alice  January      Q1

In [11]:
df.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     582.0    NaN    NaN    NaN
North      NaN    NaN  584.0    NaN
South      NaN    NaN    NaN  858.0
West       NaN  496.0    NaN    NaN

In [12]:
df.pivot_table(values='Sales',index="Region", columns="Product")

Product      A      B      C      D
Region
East     491.8    NaN    NaN    NaN
North      NaN    NaN  629.4    NaN
South      NaN    NaN    NaN  750.6
West       NaN  492.8    NaN    NaN

In [15]:
pd.crosstab(df["Region"],df["Sales"])

Sales,225,273,305,356,407,458,496,526,556,582,584,636,660,711,730,808,838,858,893,921
Region,,,,,,,,,,,,,,,,,,,,
East,1,0,0,1,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0
North,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,0
South,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1
West,0,0,1,0,1,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0

In [16]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [4]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
df1.shape

(5, 3)

In [7]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [8]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [9]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [2]:
import pandas as pd 
import numpy as np

In [3]:
dl=pd.read_csv(r"anime.csv")

In [6]:
dl.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [18]:
def extract_txt(txt):
    data=" "
    check=False
    for i in txt:
        if i == ")":
            break
        if check == True:
            data+=i
        if i =="(":
            check=True
    return data

In [19]:
dl["Eppisodes"]=dl["Title"].apply(extract_txt)

In [20]:
dl

    Rank                                              Title  Score Eppisodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10    64 eps
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07    24 eps
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06    13 eps
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06    51 eps
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05    10 eps
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04    51 eps
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04     1 eps
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04   148 eps
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04    13 eps
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03    13 eps
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03     2 eps
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02   110 eps
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99    13 eps
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99    13 eps
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98    12 eps
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94   201 eps
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94     1 eps
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93    22 eps
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93    24 eps
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91    25 eps
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91     1 eps
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89     1 eps
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88     7 eps
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88    14 eps
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87    74 eps
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84     1 eps
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84     1 eps
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83    12 eps
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83     1 eps
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82    24 eps
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82    23 eps
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81    12 eps
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81    26 eps
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80    13 eps
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80    16 eps
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79    11 eps
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79     1 eps
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79    11 eps
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78    10 eps
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78     1 eps
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77    26 eps
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77    12 eps
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76    75 eps
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75    26 eps
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75    26 eps
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74    24 eps
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73    10 eps
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72    12 eps
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71    12 eps
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71     4 eps

In [21]:
dl['Eppisodes']=dl["Eppisodes"].str.replace("eps","")

In [22]:
dl

    Rank                                              Title  Score Eppisodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [23]:
dl['Eppisodes']=dl['Eppisodes'].astype(int)

In [24]:
dl

    Rank                                              Title  Score  Eppisodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10         64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07         24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06         13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06         51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05         10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04         51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04          1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04        148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04         13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03         13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03          2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02        110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99         13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99         13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98         12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94        201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94          1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93         22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93         24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91         25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91          1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89          1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88          7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88         14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87         74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84          1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84          1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83         12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83          1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82         24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82         23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81         12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81         26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80         13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80         16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79         11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79          1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79         11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78         10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78          1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77         26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77         12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76         75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75         26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75         26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74         24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73         10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72         12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71         12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71          4

In [25]:
dl["Eppisodes"].dtype

dtype('int64')

In [31]:
def date_extract(txt):
    data=""
    for i in range(len(txt)):
        if txt[i]==")":
            for j in range(i+1,i+20):
                data+=txt[j]
    return data

In [32]:
dl["Date"]=dl["Title"].apply(date_extract)

In [33]:
dl

,Rank,Title,Score,Eppisodes,Date
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [34]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

dl['Months'] = dl['Date'].apply(calculate_total_months)

In [35]:
dl

,Rank,Title,Score,Eppisodes,Date,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,8

In [38]:
dl[dl["Score"]==dl["Score"].max]

Empty DataFrame
Columns: [Rank, Title, Score, Eppisodes, Date, Months]
Index: []